skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
t22 = "6sC5C8VFoTpEZQVn3YK9EUSd5g3Cs6zTT3HCDBGQkyo4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
